apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrm-backend
  template:
    metadata:
      labels:
        app: hrm-backend
    spec:
      containers:
        - name: hrm-backend
          image: public.ecr.aws/s4z8s2t9/repo-hrm/hrm-backend
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: your-app-secret
                  key: spring_datasource_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: your-app-secret
                  key: spring_datasource_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: your-app-secret
                  key: spring_datasource_password